services:
  api-getway:
    build: ./api-getway
    ports:
      - "8000:8000"
    # --- CRITICAL FIX: ENVIRONMENT VARIABLES ---
    environment:
      # Use the service name (user-service) as the hostname
      USER_SERVICE_URL_DOCKER: http://user-service:8001

      # Use the service name (product-service) as the hostname
      PRODUCT_SERVICE_URL_DOCKER: http://product-service:8002

      # Use the service name (order-service) as the hostname
      ORDER_SERVICE_URL_DOCKER: http://order-service:8003
    # ---------------------------------------------
    depends_on:
      - user-service
      - product-service
      - order-service
  
  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
  
  product-service:
    build: ./product-service
    ports:
      - "8002:8002"
  
  order-service:
    build: ./order-service
    ports:
      - "8003:8003"
  # Seperate database for user microservice
  user-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    volumes:
      - user_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # Seperate database for product microservice
  product-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdb
    volumes:
      - user_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # Seperate database for order microservice
  order-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orderdb
    volumes:
      - user_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  volumes:
    user_data:
    product_data:
    order_data: