services:
  api-getway:
    build: ./api-getway
    ports:
      - "8000:8000"
    # --- CRITICAL FIX: ENVIRONMENT VARIABLES ---
    environment:
      # Use the service name (user-service) as the hostname
      USER_SERVICE_URL_DOCKER: http://user-service:8001

      # Use the service name (product-service) as the hostname
      PRODUCT_SERVICE_URL_DOCKER: http://product-service:8002

      # Use the service name (order-service) as the hostname
      ORDER_SERVICE_URL_DOCKER: http://order-service:8003
    # ---------------------------------------------
    depends_on:
      - user-service
      - product-service
      - order-service
  
  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@user-db:5432/userdb
    depends_on:
      - user-db
  
  product-service:
    build: ./product-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:password@product-db:5432/productdb
    depends_on:
      - product-db
  order-service:
    build: ./order-service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:password@order-db:5432/orderdb
    depends_on:
      - order-db
  # Seperate database for user microservice
  user-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    volumes:
      - user_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # for avoid pgsql port conflict set the port maping properly [Each must have a unique host port]
  # Seperate database for product microservice
  product-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdb
    volumes:
      - product_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # for avoid pgsql port conflict set the port maping properly [Each must have a unique host port]
  # Seperate database for order microservice
  order-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orderdb
    volumes:
      - order_data:/var/lib/postgresql/data
    ports:
      - "5434:5432" # for avoid pgsql port conflict set the port maping properly [Each must have a unique host port]
volumes:
  user_data:
  product_data:
  order_data: